### ISSUE TITLE
Can't find  ''neutral_smpl_with_cocoplustoesankles_reg.pkl" file

### ISSUE THREAD

**Issue by xianzhongma** [Arthur151/DSD-SATN#17]
Hi, I cannot find  the pre-trained models and statistical model(the Google Drive link in README.md has expired). Could you please give a new link? Thanks a lot!

**Comment by Arthur151** [comment]
I am sorry? I have update the google drive link!
https://drive.google.com/drive/folders/175kdMl6emciTRFJlyKYTiEDaMABBjLp4?usp=sharing
