### ISSUE TITLE
training and webcam demo code

### ISSUE THREAD

**Issue by wolf943134497** [Arthur151/DSD-SATN#4]
Hi @Arthur151   Thanks for your excellent work!
When will you release the training and webcam demo code?  
Thanks!

**Comment by Arthur151** [comment]
Sorry for the delay! I have been doing the code release of my other work. The code for the webcam is almost finished. I will commit to this issue as soon I update the code. Thanks for your attention!

**Comment by wolf943134497** [comment]
wait in hope!  Thanks!
