### ISSUE TITLE
Questions about evaluation

### ISSUE THREAD

**Issue by zw1003855799** [Arthur151/DSD-SATN#5]
It seems that you are using gt keyp2d in evaluation,  [https://github.com/Arthur151/DSD-SATN/blob/1fdbe530cd6e6985ec5dd0446b3ec04fa7f668bd/src/base.py#L146](url), it's unreasonable.

**Comment by Arthur151** [comment]
Thanks for your interest.
It is just named as "kps_gt" and not used in evaluation.  Actually, we just use the GT 2D keypoint locations as the guidance for faster convergance in the first training epoch. In evaluation, we take the openpose result as input in some complex in-the-wild condition, which boost the performance. I think it is reasonable and acceptable.

**Comment by zw1003855799** [comment]
Thanks for your reply!
